# vib
base: ghcr.io/vanilla-os/pico:main
name: VanillaOS minimal
id: VanillaOS-minimal
stages:
  - id: build
    base: debian:sid-slim
    singlelayer: false
    labels:
      maintainer: Thomas Brugman
    args:
      DEBIAN_FRONTEND: noninteractive
    runs:
      commands:
        - echo 'APT::Install-Recommends "0";' > /etc/apt/apt.conf.d/01norecommends
    modules:
      - name: update
        type: shell
        commands:
          - apt update || { echo 'Failed to update APT'; exit 1; }
      - name: vib
        type: go
        source:
          type: git
          url: https://github.com/vanilla-os/vib
          branch: main
          commit: latest
        buildVars:
          GO_OUTPUT_BIN: /usr/bin/vib
      - name: install-dependencies
        type: shell
        commands:
          - apt install -y golang ca-certificates flatpak qemu qemu-kvm libvirt-daemon-system libvirt-clients virt-manager gnome-boxes gnome-shell-extensions gnome-shell-extension-appindicator
      - name: add-flathub
        type: shell
        commands:
          - flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo || { echo 'Failed to add flathub'; exit 1; }
      - name: install-flatpaks
        type: shell
        commands:
          - |
            for app in com.google.Chrome com.visualstudio.code it.mijorus.gearlever com.jeffser.Alpaca com.mattjakeman.ExtensionManager; do
              flatpak install -y flathub "$app" || { echo "Failed to install $app"; exit 1; }
            done
      - name: activate-extensions
        type: shell
        commands:
          - |
            for extension in dash-to-dock@gmx.de appindicator@ubuntu.com blur-my-shell@aunor.github.com; do
              gnome-extensions enable "$extension" || { echo "Failed to enable $extension"; exit 1; }
            done
